### ISSUE TITLE
look into using dplyr to query directly from database (skip VIEWs)

### ISSUE THREAD

**Issue by atn38** [BLE-LTER/MetaEgress#4]
`dplyr` can connect to PostgreSQL directly and query from a database. in other words, there's no need for the `mb2eml_r` schema because we can construct dataframes equivalent to `mb2eml_r` VIEWs directly from within R. This is different than our current approach. 

Potential gains:

- less infrastructure to maintain in metabase
- more mobile: right now if we want to change the query for a VIEW or add one, metabase needs to be updated and all our users need to update their core-mb installation. Not ideal once core-mb has been distributed.

Might be some upfront work, but there is no need to revamp anything once metadata has been queried in. We can reuse the structure we have now.

@lkuiucsb what do you think?

**Comment by lkuiucsb** [comment]
I was asking the same question two years ago and the feedback is "You really don't want to do that". 
1. Allowing R code to access views instead of core-metabase is due to security. View is abstract layer and it prevents a "hacker" to get into your core structure. It is a common strategy for data management in the back end of a website too. 
2. Different people might have different core-metabase structure. More column could be added or column names could be changed to adopt their own traditions of how they want to manage their metadata. View is a layer to allow people to have a different core-metabase but have the same view structure, just for R to work. 
3. This view is purposely designed for our R code. Some other program (e.g. python) might require different view. So the mb2eml_r is a layer that accommodate our need, at this stage.  Attaching this schema in the core-metabase is because we believe that these views are a direct way to view the full EML-required information.

**Comment by atn38** [comment]
I get the need for VIEWs now 😆
